### ISSUE TITLE
RangeError when trying to get method name

### ISSUE THREAD

**Issue by jonjon1123** [zubairehman/Flogs#22]
I am getting an error when calling any of the log methods (FLog.info, etc.) while in a method that is not directly inside of a class. I can get around this by manually passing in the method, but there seems to be a bug when this library tries to figure out the method name when the method is not directly in a class.

Code:
```
final logLevelReducer = combineReducers<LogLevel>([
  new TypedReducer<LogLevel, SetLogLevelAction>(_setLogLevel),
]);

LogLevel _setLogLevel(LogLevel logLevel, dynamic action) {
  final LogLevel _newLogLevel = action.logLevel;
  FLog.getDefaultConfigurations()..activeLogLevel = _newLogLevel;
  
  // Error occurs here
  FLog.info(text: 'LogLevel set to: ${FLog.getDefaultConfigurations().activeLogLevel}');

  return _newLogLevel;
}
```

Note: This code is in its own file. The `logLevelReducer` is used by a different class in another file like so:
```
AppState appReducer(AppState state, dynamic action) {
  return new AppState(
    ...
    logLevel: logLevelReducer(state.logLevel, action),
  );
}
```

Error stacktrace:
```
E/flutter ( 4823): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: 1
E/flutter ( 4823): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
E/flutter ( 4823): #1      FLog._logThis (package:f_logs/model/flog/flog.dart:390:63)
E/flutter ( 4823): #2      FLog.info (package:f_logs/model/flog/flog.dart:99:5)
E/flutter ( 4823): #3      _setLogLevel (package:bowlr/reducers/log_level_reducer.dart:19:8)
E/flutter ( 4823): #4      TypedReducer.call (package:redux/src/utils.dart:111:14)
E/flutter ( 4823): #5      combineReducers.<anonymous closure> (package:redux/src/utils.dart:259:22)
E/flutter ( 4823): #6      appReducer (package:bowlr/reducers/app_state_reducer.dart:56:30)
E/flutter ( 4823): #7      Store._createReduceAndNotify.<anonymous closure> (package:redux/src/store.dart:235:21)
E/flutter ( 4823): #8      TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #9      Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #10     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #11     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #12     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #13     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #14     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #15     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #16     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #17     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #18     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #19     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #20     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #21     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #22     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #23     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #24     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #25     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #26     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #27     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #28     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #29     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #30     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #31     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #32     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #33     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #34     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #35     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #36     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #37     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #38     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #39     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #40     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #41     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #42     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #43     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #44     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #45     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #46     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #47     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #48     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 4823): #49     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 4823): #50     TypedMiddleware.call (package
```

**Comment by zubairehman** [comment]
@jonjon1123 make sure 
```  
final LogLevel _newLogLevel = action.logLevel;
```
doesn't return null, else Flog will throw an exception (EXCEPTION_NULL_LOGS_LEVEL) and won't be able to write logs in DB
