### ISSUE TITLE
TypeCast error when calling getAllSortedByFilter() method

### ISSUE THREAD

**Issue by arteminthesky** [zubairehman/Flogs#51]
Hi!
i am trying to call a method getAllSortedByFilter() and get this error
It looks like something went wrong when migrating to null safety
```
type 'Future<List<RecordSnapshot<int, Map<String, Object?>>>>' is not a subtype of type 'FutureOr<List<RecordSnapshot<int, Map<String, Object>>>>' in type cast 

 #0      FlogDao.getAllSortedByFilter (package:f_logs/data/local/flog_dao.dart:85:7)
<asynchronous suspension>
#1      FLog.getAllLogsByFilter (package:f_logs/model/flog/flog.dart:300:14)
<asynchronous suspension>
```

**Comment by draganjovanovic1** [comment]
The same happens for `getAllLogs` call.

```
... type 'Future<List<RecordSnapshot<int, Map<String, Object?>>>>' is not a subtype of type 'FutureOr<List<RecordSnapshot<int, Map<String, Object>>>>' in type cast] [LogLevel.ERROR] [19 May 2021 01:52:37 PM] [#0      FlogDao.getAllLogs (package:f_logs/data/local/flog_dao.dart:100:7)
I/flutter (21997): <asynchronous suspension>
I/flutter (21997): #1      FLog.getAllLogs (package:f_logs/model/flog/flog.dart:282:14)
...
```

**Comment by draganjovanovic1** [comment]
Pull request created: https://github.com/zubairehman/Flogs/pull/52

**Comment by jawa0919** [comment]
same here

**Comment by draganjovanovic1** [comment]
Temp solution

**Comment by BenRGH** [comment]
Had to change the url to https://github.com/draganjovanovic1/Flogs.git for it to work, but thanks.
Shame this hasn't gone into master yet.

**Comment by zubairehman** [comment]
Hi,
The latest version of flogs (v2.0.1) has been released, please try that out and let me know if the issue persists.
Thanks
